
services:
  app_proxy:
    environment:
      # This must point to <app-id>_<service-name>_1
      APP_HOST: umbrelos-utilities-watermark-service_server_1
      APP_PORT: 9099

  server:
    image: ghcr.io/bold-iodev/umbrelos-utilities-watermark-service:1.0.0
    restart: on-failure
    stop_grace_period: 1m
    # Map persistent directories into the container. Umbrel defines $APP_DATA_DIR
    # to store your app's data. We mount the image uploads and processed outputs
    # there so they persist across upgrades.
    volumes:
      - ${APP_DATA_DIR}/images:/app/images
      - ${APP_DATA_DIR}/outputs:/app/outputs
    # Expose port 9009 internally; the app_proxy handles external routing.
    ports:
      - "9099:9099"
